/**
 * The job-sites directory.
 *
 * Data, not code: a flat list the Job Sites tab searches and filters. It ships
 * in the bundle because a local-first app has nowhere else to put it, and
 * because a directory that needs a network call is a directory that is empty
 * on the plane.
 *
 * Every entry was curated per sector and then HTTP-checked — 114 candidates
 * probed and deduplicated down to the list below. A directory whose links are
 * dead is worse than no directory, so that check is part of how this file is
 * maintained rather than a one-off.
 *
 * Two conventions worth keeping when adding to it:
 *
 *  - **Weaknesses are not optional and not softened.** "Full of ghost jobs",
 *    "discontinued its RSS feeds", "has not recovered from the 2025
 *    bankruptcy". A directory that only praises is an advert, and the reader
 *    finds out the hard way. If a site seems to have no honest weakness, you
 *    have not used it enough.
 *  - **`alerts` is the highest-value field here.** It records whether a site
 *    can tell you about a new posting without you visiting it — email, rss,
 *    both, or none. That is the difference between checking twenty sites a day
 *    and being told, and it is the groundwork for saved searches.
 *
 * Nothing here is fetched, scraped or proxied. These are links.
 */

export type SiteAlerts = "email" | "rss" | "both" | "none";

export interface JobSite {
  name: string;
  url: string;
  category: string;
  /** One line, under about 18 words. */
  blurb: string;
  strengths: string[];
  /** Never empty. See the note above. */
  weaknesses: string[];
  alerts: SiteAlerts;
}

/** Categories present in the data, in display order. "All" is synthesised by the UI. */
export const JOB_SITE_CATEGORIES: string[] = ["general","remote","tech","startup","freelance","design","creative","product","admin","finance","nonprofit","academic","uk","europe"];

export const JOB_SITE_CATEGORY_LABEL: Record<string, string> = {
  general: "General",
  remote: "Remote",
  tech: "Tech",
  startup: "Startups",
  freelance: "Freelance",
  design: "Design",
  data: "Data",
  product: "Product",
  admin: "Admin & PA",
  healthcare: "Healthcare",
  finance: "Finance",
  ops: "Operations",
  creative: "Creative",
  nonprofit: "Nonprofit",
  academic: "Academic",
  uk: "UK",
  europe: "Europe",
  us: "US",
};

export const ALERT_LABEL: Record<SiteAlerts, string> = {
  email: "Email alerts",
  rss: "RSS",
  both: "Email + RSS",
  none: "No alerts",
};

export const JOB_SITES: JobSite[] = [
  {
    name: "Indeed",
    url: "https://www.indeed.com/jobs",
    category: "general",
    blurb: "The largest job aggregator worldwide, combining scraped company postings with paid employer listings.",
    strengths: ["Highest raw volume in almost every country, including admin, PA and hourly roles", "Solid filters for date posted, salary, contract type and remote"],
    weaknesses: ["Massive duplication — the same role reposted by three staffing agencies", "Discontinued its RSS feeds, so email is the only subscription route; many listings are stale or already filled"],
    alerts: "email",
  },
  {
    name: "LinkedIn Jobs",
    url: "https://www.linkedin.com/jobs/",
    category: "general",
    blurb: "A job board bolted onto a professional network, strong for referrals and recruiter contact.",
    strengths: ["Shows who you know at the company before you apply", "Alerts fire fast on new postings; recruiters are reachable directly"],
    weaknesses: ["Easy Apply draws hundreds of applicants per role, so response rates are dire", "Full of ghost jobs and pipeline-building posts; salary usually hidden"],
    alerts: "email",
  },
  {
    name: "Google for Jobs",
    url: "https://www.google.com/search?q=jobs+near+me&udm=8",
    category: "general",
    blurb: "A search-results widget aggregating postings from job boards and employer career pages.",
    strengths: ["Deduplicates the same role across boards better than most aggregators", "Surfaces employer career-page postings that never reach the big boards"],
    weaknesses: ["Not a real site — no saved-jobs list, no profile, shallow filters", "Availability and feature set vary by country and language; Google states it is not available everywhere"],
    alerts: "email",
  },
  {
    name: "HiringCafe",
    url: "https://hiringcafe.com/",
    category: "general",
    blurb: "Crawls company career pages directly, indexing roughly 47,000 employer-posted jobs.",
    strengths: ["Pulls straight from Greenhouse, Lever and Workday about twice a day, so listings are employer-posted rather than recruiter reposts", "Free, with unusually deep filters: funding stage, company size, benefits, shift, salary and education"],
    weaknesses: ["Email digests are noticeably delayed and there are no push notifications — it rewards manual checking", "Web-only with no mobile app, and it defaults to your detected country, which quietly buries results if you are searching another market"],
    alerts: "email",
  },
  {
    name: "Adzuna",
    url: "https://www.adzuna.com/search",
    category: "general",
    blurb: "UK-founded aggregator with unusually good salary data and job-market statistics.",
    strengths: ["Estimates salary on postings that hide it, and the salary filter actually works", "Free public API if you ever want the data programmatically"],
    weaknesses: ["Aggregated inventory means the same job surfaces from three different sources", "Thin outside its core UK, US and Australia markets"],
    alerts: "email",
  },
  {
    name: "Glassdoor",
    url: "https://www.glassdoor.com/Job/index.htm",
    category: "general",
    blurb: "Job listings welded to company reviews, salary reports and interview accounts.",
    strengths: ["Salary ranges and employee reviews sit right next to the posting", "Good for screening an employer before spending an hour on an application"],
    weaknesses: ["Listings are largely the same Indeed inventory (same parent company), so little unique supply", "Nags you to create an account and contribute a review to unlock content"],
    alerts: "email",
  },
  {
    name: "ZipRecruiter",
    url: "https://www.ziprecruiter.com/",
    category: "general",
    blurb: "US-focused board that pushes your CV to employers and scores your match.",
    strengths: ["Employers contact candidates directly; one-click apply is genuinely fast", "Strong on admin, clerical, customer service and hourly roles"],
    weaknesses: ["Effectively North America only — UK and Canada inventory is thin", "Relentless email volume and plenty of commission-only or staffing-mill listings"],
    alerts: "email",
  },
  {
    name: "Talent.com",
    url: "https://www.talent.com/jobs",
    category: "general",
    blurb: "Global aggregator, formerly Neuvoo, indexing employer career pages and job boards.",
    strengths: ["Better non-US coverage than most, plus a genuinely useful salary and tax calculator", "Alerts available by email and SMS on saved searches"],
    weaknesses: ["Sponsored listings dominate the top of every results page", "Aggregated feed carries heavy duplication and some already-closed roles"],
    alerts: "email",
  },
  {
    name: "SimplyHired",
    url: "https://www.simplyhired.com/",
    category: "general",
    blurb: "Indeed-family aggregator with a cleaner interface and salary estimates on most listings.",
    strengths: ["Lighter and less cluttered than Indeed while drawing on similar inventory", "Alerts set up straight from the search page, no account required"],
    weaknesses: ["Heavily overlaps Indeed's index — running both mostly duplicates your effort", "Sparse outside the US and a few English-speaking markets; the bare /search path now bounces to the homepage"],
    alerts: "email",
  },
  {
    name: "Careerjet",
    url: "https://www.careerjet.com/search/jobs",
    category: "general",
    blurb: "Multilingual aggregator indexing job boards and agency sites across dozens of countries.",
    strengths: ["Very wide country and language coverage, useful for non-English markets", "Free account gives saved searches plus daily email alerts"],
    weaknesses: ["Dated interface with weak salary and date-posted filtering", "Index-only, so every click leaves the site and duplicates are never merged"],
    alerts: "email",
  },
  {
    name: "Jooble",
    url: "https://jooble.org/",
    category: "general",
    blurb: "Aggregator spanning 60-plus countries, indexing thousands of boards and career pages.",
    strengths: ["Excellent coverage of smaller markets where Indeed's index thins out", "Alerts work without an account — toggle on, enter an email, done"],
    weaknesses: ["Pure index: nearly every result bounces you to another site, duplicates included", "Filters are basic and posting dates cannot be trusted"],
    alerts: "email",
  },
  {
    name: "Monster",
    url: "https://www.monster.com/jobs",
    category: "general",
    blurb: "Long-running general board, sold to Bold after its 2025 Chapter 11 bankruptcy.",
    strengths: ["Still reasonable inventory for admin, customer service and mid-level corporate roles", "Free saved searches with daily or weekly email alerts"],
    weaknesses: ["Volume and freshness have not recovered from the 2025 bankruptcy and ownership change", "Uploading a CV reliably triggers a wave of unrelated staffing-agency calls"],
    alerts: "email",
  },
  {
    name: "CareerBuilder",
    url: "https://www.careerbuilder.com/",
    category: "general",
    blurb: "Legacy US board, sold alongside Monster to Bold out of bankruptcy in 2025.",
    strengths: ["Long tail of clerical, admin and warehouse roles from staffing firms", "Free saved search with email alerts, no paywall"],
    weaknesses: ["Badly diminished post-bankruptcy; much inventory is recruiter reposts and lead-generation bait", "Salary rarely disclosed and posting dates are often unreliable"],
    alerts: "email",
  },
  {
    name: "Jobrapido",
    url: "https://www.jobrapido.com/",
    category: "general",
    blurb: "High-volume European aggregator built almost entirely around daily email job alerts.",
    strengths: ["Strong long-tail coverage in Italy, Germany and other continental markets", "Alerts arrive fast, which matters when applying early is most of the battle"],
    weaknesses: ["Notorious email volume, with recurring public complaints about stale and low-quality listings", "The search interface is an afterthought — you are effectively subscribing to a mailing list"],
    alerts: "email",
  },
  {
    name: "We Work Remotely",
    url: "https://weworkremotely.com/remote-jobs/all-jobs",
    category: "remote",
    blurb: "The largest remote-only board, employer-funded, weighted toward engineering, support and marketing roles.",
    strengths: ["Employers pay ~$299 per post, which prices out most staffing-agency churn and low-effort spam", "Public per-category RSS feeds plus an opt-in daily digest email — trivial to automate"],
    weaknesses: ["A reverse-chronological wall with weak filtering; salary is disclosed on a minority of posts", "Almost no administration or PA work — categories are engineering, support, sales and management"],
    alerts: "both",
  },
  {
    name: "Remote OK",
    url: "https://remoteok.com/",
    category: "remote",
    blurb: "High-volume remote board built around open salary ranges and a free public feed.",
    strengths: ["Most listings carry an actual salary range, which is rare on remote boards", "Free unauthenticated JSON API (/api) and RSS (/remote-jobs.rss), filterable by tag"],
    weaknesses: ["Aggregates hard, so the same role recurs under multiple tags and older posts linger near the top", "Crypto/Web3 and low-rate offshore roles are over-represented; effectively zero admin or PA listings"],
    alerts: "both",
  },
  {
    name: "Himalayas",
    url: "https://himalayas.app/jobs",
    category: "remote",
    blurb: "Large remote board with salary data, timezone-aware filters and public RSS feeds.",
    strengths: ["Salary ranges on most listings and timezone filtering that genuinely narrows results", "Free account, free RSS, a public API, and detailed company profiles with tech stack and benefits"],
    weaknesses: ["Volume is partly aggregated, so duplicates and stale postings surface alongside fresh ones", "Heavily tech and product-oriented; administration and PA roles are rare"],
    alerts: "both",
  },
  {
    name: "Remotive",
    url: "https://remotive.com/remote-jobs",
    category: "remote",
    blurb: "Curated remote board with a free public tier and a paid accelerator upsell.",
    strengths: ["Listings are hand-checked and region restrictions are labelled up front, not buried in the ad", "Free RSS feed at /remote-jobs/rss-feed with no account required"],
    weaknesses: ["Free tier shows roughly 2,000 of a much larger pool; fuller access and better alerts cost ~$29/mo", "Skews software, marketing and customer success; thin outside those tracks"],
    alerts: "both",
  },
  {
    name: "Working Nomads",
    url: "https://www.workingnomads.com/jobs",
    category: "remote",
    blurb: "Aggregated remote listings across tech and non-tech, with free daily or weekly digests.",
    strengths: ["Free category digests, daily or weekly, that work well as a passive background feed", "Broader category list than most remote boards — includes admin, HR, finance and management"],
    weaknesses: ["The free view is deliberately throttled; premium advertises 10x more postings, so you are seeing a sample", "Aggregated rather than sourced, so a meaningful share of links land on filled or expired roles"],
    alerts: "email",
  },
  {
    name: "Remote.co",
    url: "https://remote.co/remote-jobs",
    category: "remote",
    blurb: "Free curated remote board with 50+ categories spanning well beyond tech.",
    strengths: ["Free to browse and apply, with real depth in admin, bookkeeping, data entry and customer service", "Company profiles describe each employer's actual remote setup, not just the job ad"],
    weaknesses: ["Shares a founder and funnel with FlexJobs and steers you toward that paid product", "Modest volume and category pages that refresh slowly, so repeat visits often show the same roles"],
    alerts: "email",
  },
  {
    name: "FlexJobs",
    url: "https://www.flexjobs.com/remote-jobs",
    category: "remote",
    blurb: "Paid, human-screened board with deep admin, healthcare and customer service coverage.",
    strengths: ["Every listing and company is screened, so scams, MLM pitches and lead-gen ads are effectively absent", "By far the best remote source for administrative, PA, data entry and virtual assistant roles"],
    weaknesses: ["CHARGES THE JOBSEEKER: ~$23.95 per 4 weeks or ~$71.40/year; company name and apply link are hidden until you pay", "Much of the inventory is findable free elsewhere — you are buying screening and convenience, not exclusivity"],
    alerts: "email",
  },
  {
    name: "Virtual Vocations",
    url: "https://www.virtualvocations.com/jobs",
    category: "remote",
    blurb: "Subscription US-leaning remote board with unusually deep administrative and support coverage.",
    strengths: ["Hand-screened across 45+ categories and the strongest board anywhere for admin, PA and data entry", "Operating since 2007, with a consistent record of removing dead and fraudulent listings"],
    weaknesses: ["CHARGES THE JOBSEEKER: roughly $16–20/month, and full job details stay locked until you subscribe", "Heavily US-centric — limited practical value from the UK or Europe"],
    alerts: "email",
  },
  {
    name: "Jobspresso",
    url: "https://jobspresso.co/remote-work/",
    category: "remote",
    blurb: "Hand-curated remote board, free for jobseekers, professional roles only.",
    strengths: ["Manual curation keeps out recruiter spam, fake postings and commission-only roles", "No account or paywall — browse and apply without signing up"],
    weaknesses: ["Small: roughly a thousand live roles, and new posts trickle rather than flow", "Almost entirely software, marketing, design and support — no administration track at all"],
    alerts: "email",
  },
  {
    name: "NoDesk",
    url: "https://nodesk.co/remote-jobs/",
    category: "remote",
    blurb: "Hand-picked remote jobs plus a decade-old remote-work resource library and weekly newsletter.",
    strengths: ["Every listing is tagged by region and verified as genuinely remote rather than hybrid", "Free, no sign-up wall, and a well-edited weekly newsletter worth subscribing to on its own"],
    weaknesses: ["Curation caps volume at a handful of genuinely new roles per day", "Tech- and startup-leaning; thin for administration, healthcare or public sector"],
    alerts: "email",
  },
  {
    name: "Dynamite Jobs",
    url: "https://dynamitejobs.com/",
    category: "remote",
    blurb: "Remote board from the Tropical MBA community, weighted to small bootstrapped companies.",
    strengths: ["Unusually strong in ops, VA, customer success and marketing at small profitable businesses", "Both instant and daily/weekly email alerts, configurable across up to five categories"],
    weaknesses: ["Requires a candidate account before you can set alerts or apply to some roles", "Employers are mostly small and bootstrapped — expect tighter budgets and less structured hiring"],
    alerts: "email",
  },
  {
    name: "SkipTheDrive",
    url: "https://www.skipthedrive.com/",
    category: "remote",
    blurb: "Free US-focused work-from-home board covering customer service, admin and accounting.",
    strengths: ["Free with no registration, and genuinely broad on non-tech roles other remote boards skip", "Keyword-based email alerts by category via the create-job-alert page"],
    weaknesses: ["Largely aggregated, so duplicate entries and dead apply links are common", "Dated interface and effectively US-only postings"],
    alerts: "email",
  },
  {
    name: "Arc.dev",
    url: "https://arc.dev/remote-jobs",
    category: "remote",
    blurb: "Remote job board and vetted talent network for developers, designers and marketers.",
    strengths: ["Clean separation of full-time and freelance, with hourly rates shown on contract listings", "Emails profile-matched roles after signup, and employer screening cuts the scam rate"],
    weaknesses: ["The full board of ~7,100 jobs sits behind a signup wall — you see a teaser logged out", "The 'Arc Exclusive' placement track is a four-step vetting gauntlet skewed to 5+ years and strong English, and Arc takes a cut of your rate"],
    alerts: "email",
  },
  {
    name: "JustRemote",
    url: "https://justremote.co/remote-jobs",
    category: "remote",
    blurb: "Small curated remote board with timezone filters and a paid hidden-jobs search upsell.",
    strengths: ["Filters by country and timezone, which most remote boards simply do not offer", "Free email alerts by category via the alert signup page"],
    weaknesses: ["Low volume — you can exhaust a whole category in one sitting", "The real product is the PowerSearch subscription (~$6/mo); the free board is deliberately thin"],
    alerts: "email",
  },
  {
    name: "Real Work From Anywhere",
    url: "https://www.realworkfromanywhere.com/",
    category: "remote",
    blurb: "Lists only genuinely location-free roles, excluding remote jobs restricted to one country.",
    strengths: ["Filters out the 'remote (US only)' trap that wastes time on every other remote board", "Free, with public RSS feeds and email alerts"],
    weaknesses: ["Tiny by design — truly work-from-anywhere roles are genuinely scarce", "Skews engineering, support and marketing at small distributed startups; no admin track"],
    alerts: "both",
  },
  {
    name: "Built In",
    url: "https://builtin.com/jobs",
    category: "tech",
    blurb: "US tech-hub job board publishing salary ranges on most of its listings.",
    strengths: ["Salary bands appear on the majority of postings, often precise (e.g. $155K–175K)", "Genuinely strong non-engineering coverage — people ops, marketing, executive assistant and senior admin roles at tech companies"],
    weaknesses: ["US-only and organised around specific metros (SF, NYC, Chicago, Austin, Boston, LA, Colorado)", "Listings are left up for SEO, so a genuinely fresh post sits beside months-old reposts with no visible difference"],
    alerts: "email",
  },
  {
    name: "Dice",
    url: "https://www.dice.com/jobs",
    category: "tech",
    blurb: "Long-running US and Canada IT board, heavy on contract and consulting work.",
    strengths: ["Enormous volume — around 111,000 live results with roughly 5,000 added daily", "Best-in-class for contract, C2C, cleared/defence and enterprise stacks that startup boards ignore entirely"],
    weaknesses: ["Dominated by staffing agencies: the same role reposted by six recruiters is normal, and applying triggers cold calls within minutes", "Filters are unreliable — date and pay filters routinely return thousands of non-matching results"],
    alerts: "email",
  },
  {
    name: "TrueUp",
    url: "https://www.trueup.io/jobs",
    category: "tech",
    blurb: "Aggregates big-tech and funded-startup jobs with company intel attached to each.",
    strengths: ["Free for job seekers, with filters for funding raised, company size and YC-backing", "Attaches layoff history and Glassdoor scores to each company, so you can spot a sinking ship before applying"],
    weaknesses: ["Aggregated rather than employer-posted, so duplicates and already-filled roles get through", "No documented saved-search alert — you re-run the filters yourself; coverage is almost entirely engineering, data and product"],
    alerts: "none",
  },
  {
    name: "Wellfound",
    url: "https://wellfound.com/jobs",
    category: "startup",
    blurb: "Startup job marketplace, formerly AngelList Talent, with salary and equity shown upfront.",
    strengths: ["Salary and equity ranges are mandatory on listings — you rarely waste a conversation discovering the band", "Saved searches with daily or weekly email alerts, and real coverage of ops, marketing and sales alongside engineering"],
    weaknesses: ["Applying requires building a Wellfound profile; you cannot simply attach a CV and go", "Volume is inflated by seed-stage posts that sit unattended for months — the 130k figure is not 130k live employers"],
    alerts: "email",
  },
  {
    name: "Welcome to the Jungle",
    url: "https://www.welcometothejungle.com/en/jobs",
    category: "startup",
    blurb: "Otta's successor: curated tech and startup roles across France, the UK and US.",
    strengths: ["Job alerts arrive as a daily digest of new matches once you save a search", "Company profiles carry video, team and salary detail rather than a bare listing"],
    weaknesses: ["otta.com now redirects here and the old Otta app is fully login-gated — you cannot browse it logged out", "French listings dominate the index, so UK and US volume is noticeably thinner than Otta's was standalone"],
    alerts: "email",
  },
  {
    name: "Y Combinator's Work at a Startup",
    url: "https://www.workatastartup.com/jobs",
    category: "startup",
    blurb: "Job board for YC-funded startups where one profile reaches hundreds of companies.",
    strengths: ["Every company is YC-funded and small enough that you often message a founder directly", "Listings are browsable without an account, and the single-profile application removes repetitive form-filling"],
    weaknesses: ["The model inverts: you post a profile and wait to be contacted, and there are no saved-search email alerts", "Applying needs a YC account, and the mix is heavily engineering with thin product, ops and no admin"],
    alerts: "none",
  },
  {
    name: "Startup Jobs",
    url: "https://startup.jobs/",
    category: "startup",
    blurb: "Broad startup board spanning engineering, design, marketing, sales and operations roles.",
    strengths: ["Wider role mix than most startup boards — sales, marketing and ops sit alongside engineering", "Salary pages built from real postings give a usable benchmark by location"],
    weaknesses: ["New listings are held back 24 hours unless you pay $7/month for Pro, which also gates the salary filter and instant alerts", "The free feed carries sponsored posts mixed into results"],
    alerts: "email",
  },
  {
    name: "Top Startups",
    url: "https://topstartups.io/jobs/",
    category: "startup",
    blurb: "Jobs at recently funded startups, tagged with funding round, size and investors.",
    strengths: ["Funding stage and round size shown next to every company, so you can filter for actual runway", "Around 14,800 jobs, updated daily, free to browse with no account"],
    weaknesses: ["No salary on the listings themselves — compensation sits in a separate database you have to cross-reference", "Alerts are a curated Substack newsletter, not a saved search you control"],
    alerts: "email",
  },
  {
    name: "HN Hiring",
    url: "https://hnhiring.com/",
    category: "startup",
    blurb: "Searchable, filterable mirror of the monthly Hacker News Who Is Hiring threads.",
    strengths: ["Turns the raw thread into something usable — 100+ city pages plus filtering by technology", "Confirmed current through August 2026, indexed within days of the thread posting"],
    weaknesses: ["Inherits every flaw of the source thread, including stale posts nobody removed", "Its freelancer section has not been updated since October 2025, and there are no alerts, RSS or saved searches"],
    alerts: "none",
  },
  {
    name: "Hacker News — Ask HN: Who Is Hiring?",
    url: "https://news.ycombinator.com/submitted?id=whoishiring",
    category: "startup",
    blurb: "Monthly Hacker News thread where hiring companies post their own openings directly.",
    strengths: ["Posts are written by the engineer or founder doing the hiring, not an agency, so replies actually land", "Still running — August 2026 thread drew 384 comments, posted first of each month like clockwork"],
    weaknesses: ["A raw comment thread: no filters, no search, no dedupe, and you scroll it manually", "Overwhelmingly US and remote engineering; essentially zero admin, PA or non-technical roles"],
    alerts: "none",
  },
  {
    name: "Upwork",
    url: "https://www.upwork.com/freelance-jobs/",
    category: "freelance",
    blurb: "The largest general freelance marketplace — hourly or fixed-price contracts across every discipline.",
    strengths: ["Real volume in non-tech work: VA, bookkeeping, exec support, not just dev", "Hourly contracts carry time-tracker payment protection; fixed-price uses escrow"],
    weaknesses: ["Roughly 10% off your earnings plus paid Connects (~$0.15 each) on every proposal, won or lost", "Generic briefs draw 50+ bids within hours, mostly undercutting on price"],
    alerts: "email",
  },
  {
    name: "Freelancer.com",
    url: "https://www.freelancer.com/jobs",
    category: "freelance",
    blurb: "Huge low-end bidding marketplace for projects and design contests across every category.",
    strengths: ["Publishes genuine RSS feeds — the easiest board here to pipe into a reader", "Enormous listing volume (5,000+ live) across trades, admin, design and code"],
    weaknesses: ["The most brutal race to the bottom on this list; budgets of $10–50 for real work are normal", "Constant upsells (membership tiers, bid boosts) and a high share of spam and scam posts"],
    alerts: "both",
  },
  {
    name: "PeoplePerHour",
    url: "https://www.peopleperhour.com/freelance-jobs",
    category: "freelance",
    blurb: "UK-founded marketplace mixing posted projects with fixed-price \"Hourlies\" you list yourself.",
    strengths: ["UK and European clients paying in GBP; fee tapers 20% to 7.5% to 3.5% as you bill one client", "Modest live count (~300 jobs) means far fewer bidders per brief than Upwork"],
    weaknesses: ["The fee resets to 20% for every new client, so a churny client mix keeps you at the top rate permanently", "Free proposal credits run out fast, and posted budgets skew low"],
    alerts: "email",
  },
  {
    name: "Fiverr",
    url: "https://www.fiverr.com/start_selling",
    category: "freelance",
    blurb: "Packaged-gig marketplace where buyers browse your listings instead of you pitching for work.",
    strengths: ["No proposals to write: you publish fixed-price services and let search bring buyers", "Steady demand for repeatable admin, data entry, writing and design tasks"],
    weaknesses: ["Flat 20% of every order forever — no volume discount, and Fiverr Pro pays the same cut", "No job feed at all since Buyer Requests was retired; new sellers stay invisible until reviews accumulate"],
    alerts: "none",
  },
  {
    name: "Contra",
    url: "https://contra.com/features/find-freelance-jobs",
    category: "freelance",
    blurb: "Commission-free platform for independents, strongest in design, marketing and creative contract work.",
    strengths: ["0% commission — you keep the full invoice, unusual among marketplaces", "Budgets are shown on listings and there is no bid-undercutting format"],
    weaknesses: ["Full access to the opportunity feed sits behind paid Contra Pro", "Thin outside creative and startup work; very little admin, ops or enterprise contract"],
    alerts: "email",
  },
  {
    name: "Toptal",
    url: "https://www.toptal.com/freelance-jobs",
    category: "freelance",
    blurb: "Vetted network placing senior developers, designers, finance and project talent at premium rates.",
    strengths: ["Clients are vetted and pay properly; you apply to briefs rather than bid against a crowd", "Covers finance and project-management contracts, not only engineering"],
    weaknesses: ["Multi-stage screening is slow and the pass rate is famously low — weeks before you see any work", "Matchers control your deal flow, so a quiet month is opaque and impossible to debug"],
    alerts: "email",
  },
  {
    name: "Braintrust",
    url: "https://www.usebraintrust.com/jobs",
    category: "freelance",
    blurb: "Enterprise contract network that charges talent nothing; the client pays the platform fee.",
    strengths: ["0% talent fee — the 15% is billed to the client, so your rate is your take-home", "Fortune 1000 contracts spanning engineering, product, design, ops, finance and marketing"],
    weaknesses: ["You must pass vetting/certification before you can actually apply — browsing is not access", "Roles skew US-hours enterprise, and the crypto-token layer adds noise most freelancers ignore"],
    alerts: "email",
  },
  {
    name: "Catalant",
    url: "https://catalant.com/for-independent-consultants/",
    category: "freelance",
    blurb: "Marketplace for independent consultants on Fortune 500 strategy, PMO and transformation projects.",
    strengths: ["Engagements run for months or years at consulting rates, not task-level gig pricing", "Suits senior product, ops and strategy people who would be underpriced on Upwork"],
    weaknesses: ["Profile approval gate followed by opaque matching — long idle stretches are normal", "US-centric, and MBB / Big Four pedigree is heavily favoured in matching"],
    alerts: "email",
  },
  {
    name: "Gun.io",
    url: "https://gun.io/find-work/",
    category: "freelance",
    blurb: "Small vetted network matching senior freelance developers to long US-rate contracts.",
    strengths: ["Senior rates in the $100–200/hr band with no platform cut skimmed off your rate", "Human vetting including a live technical interview keeps client quality high"],
    weaknesses: ["Developers only, and volume is tiny — it is a pipeline, not a browsable board", "Nothing to search: you wait to be matched, which can take weeks or months"],
    alerts: "email",
  },
  {
    name: "IxDF Jobs",
    url: "https://ixdf.org/jobs",
    category: "design",
    blurb: "Interaction Design Foundation's aggregated UX board with profile-based job matching.",
    strengths: ["Over 10,000 live UX roles across 108 countries — by far the widest UX net", "Matching surfaces roles by skill rather than keyword guessing"],
    weaknesses: ["Aggregated from elsewhere, so duplicates and already-filled roles slip through", "No salary data, and every path funnels toward a paid IxDF membership"],
    alerts: "email",
  },
  {
    name: "Dribbble Jobs",
    url: "https://dribbble.com/jobs",
    category: "design",
    blurb: "Job board attached to the visual-design community, mostly UI, brand and graphic roles.",
    strengths: ["Postings are native and paid-for, not scraped, so listings are real openings", "Skews toward brand and visual craft work that generic tech boards never surface"],
    weaknesses: ["Almost no salary disclosure anywhere on the board", "Small — roughly 50 live roles at a time, heavy on agency and early-stage startup UI"],
    alerts: "none",
  },
  {
    name: "Authentic Jobs",
    url: "https://authenticjobs.com/",
    category: "design",
    blurb: "Twenty-year-old board for designers, developers and creative professionals, freelance and full-time.",
    strengths: ["Publishes a real RSS feed — rare, and exactly what a saved-search workflow needs", "Curated rather than scraped, so recruiter noise stays low"],
    weaknesses: ["Volume has shrunk considerably since its 2010s peak", "Skews US and web-agency; little in-house enterprise or European work"],
    alerts: "both",
  },
  {
    name: "AIGA Design Careers",
    url: "https://designcareers.aiga.org/jobs",
    category: "design",
    blurb: "The US graphic-design profession's own board, run by AIGA for member designers.",
    strengths: ["~400 listings including in-house, agency and nonprofit roles that never reach tech boards", "Genuinely strong for print, brand, packaging and environmental graphics"],
    weaknesses: ["Membership pitch throughout, and some listing features are member-only", "Almost entirely US-based; posting fees skew it toward established employers"],
    alerts: "email",
  },
  {
    name: "Coroflot",
    url: "https://www.coroflot.com/design-jobs",
    category: "design",
    blurb: "Long-running design job board and portfolio site, strongest in industrial and product design.",
    strengths: ["Best board anywhere for industrial, furniture, footwear and hardware design roles", "Job Agents are real saved-search email alerts, not a generic newsletter"],
    weaknesses: ["Thin volume — often only a dozen or so live roles per discipline", "Site and portfolio tooling feel dated next to Dribbble or Behance"],
    alerts: "email",
  },
  {
    name: "Dezeen Jobs",
    url: "https://www.dezeenjobs.com/jobs/",
    category: "design",
    blurb: "Architecture, interiors and product design roles from the Dezeen design-media audience.",
    strengths: ["Daily email alerts and 100,000+ subscribed jobseekers, so studios actually post here", "Strong for practices and studios, especially London and wider Europe"],
    weaknesses: ["Architecture and interiors dominate; almost nothing digital, UX or product", "Pay is usually 'competitive' rather than a number"],
    alerts: "email",
  },
  {
    name: "Behance Jobs (Adobe Talent)",
    url: "https://www.behance.net/joblist",
    category: "creative",
    blurb: "Adobe's creative job board, portfolio-first, mixing freelance gigs and full-time creative roles.",
    strengths: ["Around a thousand live roles across freelance, contract and full-time, refreshed daily", "Many listings show an actual rate or salary range"],
    weaknesses: ["Needs an Adobe account, and your Behance portfolio is effectively the application", "Heavy on illustration, motion and graphic work; thin for UX research or product design"],
    alerts: "none",
  },
  {
    name: "Mind the Product Jobs",
    url: "https://www.mindtheproduct.com/jobs/",
    category: "product",
    blurb: "Small curated product board from the biggest product-management community and conference series.",
    strengths: ["Most listings show a real salary range, unusual for product roles", "Covers product design, ops, analytics and PMM, not just PM"],
    weaknesses: ["Tiny — only a handful of live roles at any one time, so it is a supplement rather than a primary board"],
    alerts: "none",
  },
  {
    name: "SecsintheCity",
    url: "https://www.secsinthecity.co.uk/jobs/",
    category: "admin",
    blurb: "The UK's only dedicated job board for PAs, EAs, secretaries and office managers.",
    strengths: ["Only UK board built purely for business support — no filtering tech roles out of admin searches", "Offers both email alerts and an RSS feed, rare for a UK board; ~44 pages of live vacancies"],
    weaknesses: ["Overwhelmingly London and legal/finance secretarial; thin outside the M25", "Most postings are agency-placed, so the same role appears under several consultancies"],
    alerts: "both",
  },
  {
    name: "Robert Half",
    url: "https://www.roberthalf.com/us/en/jobs/all/administrative-and-customer-support",
    category: "admin",
    blurb: "US staffing firm listing administrative, customer-support, finance and accounting roles.",
    strengths: ["Hourly or annual pay range shown on nearly every posting — rare for a US staffing site", "Covers both the admin and the finance/accounting sides, useful if you straddle the two"],
    weaknesses: ["Around 230 live admin roles nationally and heavily weighted to temp and contract-to-hire", "You are placed by a recruiter, so the employer and the true rate are often obscured until late"],
    alerts: "email",
  },
  {
    name: "Boldly",
    url: "https://boldly.com/jobs/",
    category: "admin",
    blurb: "Remote EA firm hiring senior assistants in the US and UK as W2 employees.",
    strengths: ["Actual W2 employment with paid holiday, 401k match and employer-paid medical — not 1099 gig work", "One of the very few remote-EA firms hiring in both the US and the UK"],
    weaknesses: ["Wants 7+ years supporting senior executives; anyone earlier in their career is filtered out", "Single employer, so openings are sporadic — the signup is a talent pool, not a saved search"],
    alerts: "email",
  },
  {
    name: "BELAY",
    url: "https://belaysolutions.com/jobs",
    category: "admin",
    blurb: "US firm placing contract executive assistants, bookkeepers and marketing assistants with clients.",
    strengths: ["Hires bookkeepers and marketing assistants as well as EAs, so the ladder is broader than VA work", "Long-running 1099 contractor work with no bidding, proposals or proposal credits"],
    weaknesses: ["Around $19–23/hr, with no guaranteed hours and no guaranteed client placement", "US residents only, currently excluding CA, CO, MT, NJ, NY and PA; corporate roles require Metro Atlanta"],
    alerts: "none",
  },
  {
    name: "Time etc",
    url: "https://www.timeetc.com/work-for-us",
    category: "admin",
    blurb: "Matches experienced freelance assistants with US and UK founders needing part-time support.",
    strengths: ["Steady client flow with no pitching, bidding or proposal credits", "You pick your hours and client load, and a decision on your application often comes within the hour"],
    weaknesses: ["Freelance contractor only, from around $17/hour, with no benefits and an agency margin on top", "The average assistant bills only ~39 hours a month, so it rarely replaces a full-time income"],
    alerts: "none",
  },
  {
    name: "Prialto",
    url: "https://www.prialto.com/careers/jobs",
    category: "admin",
    blurb: "Managed virtual-assistant service hiring productivity assistants at its offshore delivery centres.",
    strengths: ["Salaried team roles with training and management, not isolated gig work", "Supports US C-suite clients, so the experience is genuinely senior-level"],
    weaknesses: ["Assistant roles are only in Guatemala City, Manila and Nairobi — nothing for US or UK-based applicants", "The Portland openings are sales and account management, not assistant work"],
    alerts: "none",
  },
  {
    name: "Athena",
    url: "https://jobs.athena.com/",
    category: "admin",
    blurb: "Premium EA firm hiring assistants offshore to support US and global executives.",
    strengths: ["Strong training and progression, including funded MBA access and weekly pay", "Clients are high-calibre founders and executives, so the CV value is real"],
    weaknesses: ["Hires only in Quezon City, Cavite, Medellín, Nairobi and Guatemala City — a US or UK applicant will not be considered", "No job alerts or saved searches; you must keep checking the Workday portal manually"],
    alerts: "none",
  },
  {
    name: "eFinancialCareers",
    url: "https://www.efinancialcareers.co.uk/jobs/accounting-finance",
    category: "finance",
    blurb: "Financial-services job board covering accounting, finance operations, risk and compliance worldwide.",
    strengths: ["Over 8,000 accounting and finance roles, including the back- and middle-office ops jobs generalist boards miss", "Separate UK and US sites with proper local coverage rather than one merged feed"],
    weaknesses: ["Almost every listing says 'Competitive' — salary transparency is close to zero", "Dominated by agency ads and skews to banking front office; junior finance-admin roles are thin"],
    alerts: "email",
  },
  {
    name: "CharityJob",
    url: "https://www.charityjob.co.uk/jobs",
    category: "nonprofit",
    blurb: "UK charity-sector board, strong on finance, operations and administration roles.",
    strengths: ["Around 1,850 live roles with salary shown on almost every listing — unusually transparent", "Deep on the ops/finance middle: finance officers, operations managers, finance directors"],
    weaknesses: ["Charity pay is materially below commercial equivalents for the same responsibility", "UK only, and many roles are fixed-term or grant-funded rather than permanent"],
    alerts: "email",
  },
  {
    name: "jobs.ac.uk",
    url: "https://www.jobs.ac.uk/search/administrative",
    category: "academic",
    blurb: "UK university jobs, including the large hidden market in higher-education administration.",
    strengths: ["Higher-education admin is a real career ladder — admissions officers, faculty administrators, research managers", "Salaries published against transparent university pay spines, with pension and leave to match"],
    weaknesses: ["Only a couple of hundred administrative roles at any time, and they close on fixed dates", "Recruitment is slow and committee-driven; account limits you to five saved alerts"],
    alerts: "email",
  },
  {
    name: "Reed",
    url: "https://www.reed.co.uk/jobs",
    category: "uk",
    blurb: "Large UK jobs board with a dedicated admin, secretarial and PA category.",
    strengths: ["Around 3,900 live admin/secretarial/PA roles inside a ~99,000-job index, refreshed daily", "Has a 'hide jobs without salary displayed' filter, which cuts the vague listings fast"],
    weaknesses: ["Salary is inconsistent — many listings say only 'Competitive'", "Heavy recruiter duplication; one vacancy can appear four times from four agencies"],
    alerts: "email",
  },
  {
    name: "Totaljobs",
    url: "https://www.totaljobs.com/jobs/",
    category: "uk",
    blurb: "High-volume UK board where most mainstream admin and office-support vacancies eventually appear.",
    strengths: ["Roughly 5,500 live admin roles plus ~900 part-time and ~400 temp — good for flexible searches", "Strong regional coverage: Leeds, Manchester, Birmingham, Glasgow all have real depth"],
    weaknesses: ["Average advertised admin salary sits near £25k — the board skews to the low end of the market", "Aggregated and agency-fed, so stale postings and reposts are common"],
    alerts: "email",
  },
  {
    name: "Civil Service Jobs",
    url: "https://www.civilservicejobs.service.gov.uk/",
    category: "uk",
    blurb: "Official UK government board and the single biggest source of public-sector admin roles.",
    strengths: ["Enormous, genuinely hidden volume of AO/EO/HEO administrative and operations posts", "Salary, grade and location are always published — no 'competitive' anywhere"],
    weaknesses: ["Success Profiles applications demand several 250-word behavioural statements per role; expect hours per application", "Dated interface behind a bot check, and hiring timelines routinely run two to four months"],
    alerts: "email",
  },
  {
    name: "Hays UK — Business Support",
    url: "https://www.hays.co.uk/jobs/business-support",
    category: "uk",
    blurb: "Global recruiter's UK business-support desk: office managers, administrators, receptionists, team assistants.",
    strengths: ["Steady flow of mid-to-senior administrator and office-manager roles across UK regions", "Applications go to a named sector consultant rather than a black-hole inbox"],
    weaknesses: ["Agency-only: you cannot see or approach the hiring employer directly", "Site is aggressively bot-protected and slow, and consultants chase you for unrelated roles once you register"],
    alerts: "email",
  },
  {
    name: "Michael Page UK — Business Support",
    url: "https://www.michaelpage.co.uk/jobs/business-support",
    category: "uk",
    blurb: "PageGroup's UK business-support listings — administrators, EAs, PAs and customer service.",
    strengths: ["Skews to better-paid corporate EA and team-assistant roles than the mass-market boards", "Job alerts can be created anonymously without registering"],
    weaknesses: ["Only ~260 live business-support roles, and Page Personnel's own UK job search now redirects here — one pool, not two", "London and Home Counties dominate; regional listings are sparse"],
    alerts: "email",
  },
  {
    name: "Office Angels",
    url: "https://www.office-angels.com/job-results",
    category: "uk",
    blurb: "UK high-street agency specialising in temp and permanent office, secretarial and PA roles.",
    strengths: ["Specialist office-support desk with real depth in temp and interim cover", "Named job alerts at your chosen frequency, set up without an account"],
    weaknesses: ["Only around 475 live roles nationally — a fraction of what a general board carries", "Everything routes through a consultant, and employer names are often withheld until you engage"],
    alerts: "email",
  },
  {
    name: "cord",
    url: "https://cord.com/search",
    category: "uk",
    blurb: "London-centric tech platform built around direct messaging with hiring managers.",
    strengths: ["Direct chat with the hiring team rather than an application black hole, plus a last-active signal showing which employers are responsive", "You can browse and express interest anonymously, so your current employer does not see you looking"],
    weaknesses: ["Overwhelmingly London with a thin New York and remote slice; engineering-dominated, almost no admin or PA work", "Recruitment agencies do post despite the direct-to-employer pitch, and there are no saved-search alerts"],
    alerts: "none",
  },
  {
    name: "YunoJuno",
    url: "https://www.yunojuno.com/freelancers",
    category: "uk",
    blurb: "UK freelance marketplace for day-rate contract briefs from brands and agencies.",
    strengths: ["No commission taken from you — the hirer pays the fee, and payment lands 14 days after timesheet", "Publishes a detailed day-rate report by discipline, so you can benchmark before quoting"],
    weaknesses: ["Vetted entry, and much of the work is matched privately rather than posted as a public brief", "London and agency-heavy in marketing, design and product; sparse outside the UK"],
    alerts: "email",
  },
  {
    name: "Malt",
    url: "https://www.malt.com/",
    category: "europe",
    blurb: "Europe's largest freelance marketplace, where clients search profiles and approach you directly.",
    strengths: ["Deep client base across France, Germany, Spain, Benelux, the Nordics and the UK", "Day-rate consulting engagements with fast guaranteed payment and liability cover included"],
    weaknesses: ["No browsable job board at all — inbound only, so a dormant profile earns nothing", "Fee terms changed several times during 2026 and differ by country (0% in Germany, tiered in France)"],
    alerts: "email",
  },
  {
    name: "freelancermap",
    url: "https://www.freelancermap.com/projects",
    category: "europe",
    blurb: "European IT and consulting contract board listing day-rate projects, heavily German-speaking.",
    strengths: ["Fully browsable without an account, 0% commission, and you contact the poster directly", "Real SAP, IT and consulting contracts with day rates, including on-site DACH roles"],
    weaknesses: ["Agency-dominated: the same contract often appears three times from competing intermediaries", "Many postings are German-language, and free accounts get only one saved-search alert"],
    alerts: "email",
  },
];
